name: start_jwt
version: 0.1.0
description: JSON Web Token implemented as a standard Dart codec.

homepage: https://github.com/bsjung/start_jwt

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  crypto: ^2.1.4
  cryptoutils: ^0.4.0

dev_dependencies:
  test: ^1.0.0
